INSERT INTO aluno (nome,
				   cpf,
				   observacao,
				   idade,
				   valor_matricula,
				   altura,
				   ativo,
				   data_nascimento,
				   hora_aula,
				   matriculado_em) 
VALUES 
                ('Severino', 
                '01234567890',
                'lorem Laborum consectetur culpa exercitation mollit.',
                30,
                250.00,
                1.75,
                TRUE,
                '1996-01-29',
                '17:30:00' ,
                '2023-06-06 10:00:00');